import type { Config } from 'tailwindcss';

const config: Config = {
  theme: {
    extend: {
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
        '40': '160px',
      },
      colors: {
        white: 'var(--ds-surface-paper)',
        black: 'var(--ds-text-primary)',
        stone: {
          50: 'var(--ds-surface-page)',
          100: 'var(--ds-surface-soft)',
          200: 'var(--ds-border-subtle)',
          300: 'var(--ds-border-strong)',
          400: 'var(--ds-text-disabled)',
          500: 'var(--ds-text-muted)',
          600: 'var(--ds-text-secondary)',
          700: 'var(--ds-text-secondary)',
          800: 'var(--ds-text-primary)',
          900: 'var(--ds-text-primary)',
          950: 'var(--ds-text-primary)',
        },
        neutral: {
          50: 'var(--ds-surface-page)',
          100: 'var(--ds-surface-soft)',
          200: 'var(--ds-border-subtle)',
          300: 'var(--ds-border-strong)',
          400: 'var(--ds-text-disabled)',
          500: 'var(--ds-text-muted)',
          600: 'var(--ds-text-secondary)',
          700: 'var(--ds-text-secondary)',
          800: 'var(--ds-text-primary)',
          900: 'var(--ds-text-primary)',
          950: 'var(--ds-text-primary)',
        },
        zinc: {
          50: 'var(--ds-surface-page)',
          100: 'var(--ds-surface-soft)',
          200: 'var(--ds-border-subtle)',
          300: 'var(--ds-border-strong)',
          400: 'var(--ds-text-disabled)',
          500: 'var(--ds-text-muted)',
          600: 'var(--ds-text-secondary)',
          700: 'var(--ds-text-secondary)',
          800: 'var(--ds-text-primary)',
          900: 'var(--ds-text-primary)',
          950: 'var(--ds-text-primary)',
        },
        gray: {
          50: 'var(--ds-surface-page)',
          100: 'var(--ds-surface-soft)',
          200: 'var(--ds-border-subtle)',
          300: 'var(--ds-border-strong)',
          400: 'var(--ds-text-disabled)',
          500: 'var(--ds-text-muted)',
          600: 'var(--ds-text-secondary)',
          700: 'var(--ds-text-secondary)',
          800: 'var(--ds-text-primary)',
          900: 'var(--ds-text-primary)',
          950: 'var(--ds-text-primary)',
        },
        slate: {
          50: 'var(--ds-surface-page)',
          100: 'var(--ds-surface-soft)',
          200: 'var(--ds-border-subtle)',
          300: 'var(--ds-border-strong)',
          400: 'var(--ds-text-disabled)',
          500: 'var(--ds-text-muted)',
          600: 'var(--ds-text-secondary)',
          700: 'var(--ds-text-secondary)',
          800: 'var(--ds-text-primary)',
          900: 'var(--ds-text-primary)',
          950: 'var(--ds-text-primary)',
        },
        amber: {
          50: 'var(--ds-warning-bg)',
          100: 'var(--ds-warning-bg)',
          200: 'var(--ds-warning-bg)',
          300: 'var(--ds-accent-gold)',
          400: 'var(--ds-accent-gold)',
          500: 'var(--ds-accent-gold)',
          600: 'var(--ds-warning)',
          700: 'var(--ds-warning-text)',
          800: 'var(--ds-warning-text)',
          900: 'var(--ds-warning-text)',
          950: 'var(--ds-warning-text)',
        },
        yellow: {
          50: 'var(--ds-warning-bg)',
          100: 'var(--ds-warning-bg)',
          200: 'var(--ds-warning-bg)',
          300: 'var(--ds-accent-gold)',
          400: 'var(--ds-accent-gold)',
          500: 'var(--ds-accent-gold)',
          600: 'var(--ds-warning)',
          700: 'var(--ds-warning-text)',
          800: 'var(--ds-warning-text)',
          900: 'var(--ds-warning-text)',
          950: 'var(--ds-warning-text)',
        },
        green: {
          50: 'var(--ds-success-bg)',
          100: 'var(--ds-success-bg)',
          200: 'var(--ds-success-bg)',
          300: 'var(--ds-success)',
          400: 'var(--ds-success)',
          500: 'var(--ds-success)',
          600: 'var(--ds-success)',
          700: 'var(--ds-success-text)',
          800: 'var(--ds-success-text)',
          900: 'var(--ds-success-text)',
          950: 'var(--ds-success-text)',
        },
        emerald: {
          50: 'var(--ds-success-bg)',
          100: 'var(--ds-success-bg)',
          200: 'var(--ds-success-bg)',
          300: 'var(--ds-success)',
          400: 'var(--ds-success)',
          500: 'var(--ds-success)',
          600: 'var(--ds-success)',
          700: 'var(--ds-success-text)',
          800: 'var(--ds-success-text)',
          900: 'var(--ds-success-text)',
          950: 'var(--ds-success-text)',
        },
        red: {
          50: 'var(--ds-danger-bg)',
          100: 'var(--ds-danger-bg)',
          200: 'var(--ds-danger-bg)',
          300: 'var(--ds-danger)',
          400: 'var(--ds-danger)',
          500: 'var(--ds-danger)',
          600: 'var(--ds-danger)',
          700: 'var(--ds-danger)',
          800: 'var(--ds-danger)',
          900: 'var(--ds-danger)',
          950: 'var(--ds-danger)',
        },
        rose: {
          50: 'var(--ds-danger-bg)',
          100: 'var(--ds-danger-bg)',
          200: 'var(--ds-danger-bg)',
          300: 'var(--ds-danger)',
          400: 'var(--ds-danger)',
          500: 'var(--ds-danger)',
          600: 'var(--ds-danger)',
          700: 'var(--ds-danger)',
          800: 'var(--ds-danger)',
          900: 'var(--ds-danger)',
          950: 'var(--ds-danger)',
        },
        blue: {
          50: 'var(--ds-info-bg)',
          100: 'var(--ds-info-bg)',
          200: 'var(--ds-info-bg)',
          300: 'var(--ds-info)',
          400: 'var(--ds-info)',
          500: 'var(--ds-info)',
          600: 'var(--ds-info)',
          700: 'var(--ds-info-text)',
          800: 'var(--ds-info-text)',
          900: 'var(--ds-info-text)',
          950: 'var(--ds-info-text)',
        },
        indigo: {
          50: 'var(--ds-info-bg)',
          100: 'var(--ds-info-bg)',
          200: 'var(--ds-info-bg)',
          300: 'var(--ds-info)',
          400: 'var(--ds-info)',
          500: 'var(--ds-info)',
          600: 'var(--ds-info)',
          700: 'var(--ds-info-text)',
          800: 'var(--ds-info-text)',
          900: 'var(--ds-info-text)',
          950: 'var(--ds-info-text)',
        },
        pink: {
          50: 'var(--ds-danger-bg)',
          100: 'var(--ds-danger-bg)',
          200: 'var(--ds-danger-bg)',
          300: 'var(--ds-accent-soft)',
          400: 'var(--ds-accent-primary)',
          500: 'var(--ds-accent-primary)',
          600: 'var(--ds-accent-hover)',
          700: 'var(--ds-accent-hover)',
          800: 'var(--ds-accent-hover)',
          900: 'var(--ds-accent-hover)',
          950: 'var(--ds-accent-hover)',
        },
        purple: {
          50: 'var(--ds-info-bg)',
          100: 'var(--ds-info-bg)',
          200: 'var(--ds-info-bg)',
          300: 'var(--ds-info)',
          400: 'var(--ds-info)',
          500: 'var(--ds-info)',
          600: 'var(--ds-info)',
          700: 'var(--ds-info-text)',
          800: 'var(--ds-info-text)',
          900: 'var(--ds-info-text)',
          950: 'var(--ds-info-text)',
        },
        text: {
          primary: 'var(--ds-text-primary)',
          secondary: 'var(--ds-text-secondary)',
          muted: 'var(--ds-text-muted)',
          disabled: 'var(--ds-text-disabled)',
          inverse: 'var(--ds-text-inverse)',
          accent: 'var(--ds-accent-primary)',
          error: 'var(--ds-danger)',
          success: 'var(--ds-success-text)',
          price: 'var(--ds-text-price)',
          'price-old': 'var(--ds-text-price-old)',
          sale: 'var(--ds-danger)',
        },
        brand: {
          terracotta: 'var(--ds-accent-primary)',
          accent: 'var(--ds-accent-primary)',
          hover: 'var(--ds-accent-hover)',
          accentSoft: 'var(--ds-accent-soft)',
          cream:   'var(--ds-surface-page)',
          paper:   'var(--ds-surface-paper)',
          ink:     'var(--ds-text-primary)',
          muted:   'var(--ds-text-muted)',
          line:    'var(--ds-border-subtle)',
          soft:    'var(--ds-surface-soft)',
          gold:    'var(--ds-accent-gold)',
          danger:  'var(--ds-danger-bg)',
          success: 'var(--ds-success-bg)',
        },
      },
      fontFamily: {
        heading: ['var(--ds-font-display)', 'serif'],
        display: ['var(--ds-font-display)', 'serif'],
        body:    ['var(--ds-font-body)', 'serif'],
        ui:      ['var(--ds-font-ui)', 'serif'],
        label:   ['var(--ds-font-label)', 'serif'],
        serif:   ['var(--ds-font-display)', 'serif'],
        sans:    ['var(--ds-font-body)', 'serif'],
      },
      fontSize: {
        'display-xl': ['var(--ds-text-display-xl)', { lineHeight: 'var(--ds-leading-tight)', letterSpacing: 'var(--ds-type-heading-tracking)' }],
        'display-lg': ['var(--ds-text-display-lg)', { lineHeight: 'var(--ds-leading-tight)', letterSpacing: 'var(--ds-type-heading-tracking)' }],
        'display-md': ['var(--ds-text-display-md)', { lineHeight: 'var(--ds-leading-tight)', letterSpacing: 'var(--ds-type-heading-tracking)' }],
        'display-sm': ['var(--ds-text-display-sm)', { lineHeight: 'var(--ds-leading-snug)', letterSpacing: 'var(--ds-type-heading-tracking)' }],
        'body-xl': ['var(--ds-text-body-xl)', { lineHeight: 'var(--ds-leading-relaxed)' }],
        'body-lg': ['var(--ds-text-body-lg)', { lineHeight: 'var(--ds-leading-normal)' }],
        'body-md': ['var(--ds-text-body-md)', { lineHeight: 'var(--ds-leading-normal)' }],
        'body-sm': ['var(--ds-text-body-sm)', { lineHeight: 'var(--ds-leading-normal)' }],
        'body-xs': ['var(--ds-text-body-xs)', { lineHeight: 'var(--ds-leading-normal)', letterSpacing: 'var(--ds-type-body-tracking)' }],
      },
      maxWidth: {
        prose: 'var(--ds-prose-width)',
        heading: 'var(--ds-heading-width)',
        caption: 'var(--ds-caption-width)',
        content: 'var(--ds-content-width)',
        narrow: 'var(--ds-narrow-width)',
      },
      borderRadius: {
        sm: 'var(--ds-radius-sm)', // 4px — buttons, badges
        md: 'var(--ds-radius-md)', // 8px — inputs, chips
        lg: 'var(--ds-radius-lg)', // 12px — cards, modals
      },
    },
  },
};

export default config;
